---

- name: Add Root SSH Keys
  authorized_key: user=root key={{ item }}
  with_items: #TODO add the keys from saltstack and make this it's own task/role
     - http://github.com/hef.keys
     - http://github.com/dkoppel.keys
     - http://github.com/loansindi.keys
     - http://github.com/bjonnh.keys
     - http://github.com/codersquid.keys

- name: Install Dependencies
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
     - python
     - postgresql
     - python2-psycopg2
     - redis
     - git

- name: Create ps1auth User and Application Root Directory
  user: name=ps1auth state=present home={{ app_root }}

- name: Clone github repository
  git: repo=https://github.com/hef/ps1auth dest={{ app_root }}/app

- name: Setup Python Environment
  pip: requirements={{ app_root }}/app/requirements/production.txt state=present virtualenv={{ app_root }}/venv

- name: Setup Bash Environment
  template: src=bashrc.j2 dest={{ app_root }}/.bashrc

- name: Configure ps1auth.conf
  template: src=ps1auth.conf.j2 dest={{ app_root }}/etc/ps1auth.conf

- name: Configure config.sh
  template: src=config.sh.j2 dest={{ app_root }}/config.sh

# This doesn't work until you manually init the DB and start PostgreSQL
- name: Create PostgreSQL User
  sudo: postgres
  postgresql_user: name=ps1auth role_attr_flags=SUPERUSER state=present

- name: Create PostgreSQL DB
  sudo: postgres
  postgresql_db: name=ps1auth encoding=UTF-8 lc_collate=en_US.UTF-8 owner=ps1auth

- name: Configure systemd (ps1auth-web.service)
  template: src=ps1auth-web.service.j2 dest=/etc/systemd/system/ps1auth-web.service

- name: Configure systemd (ps1auth-web.socket)
  template: src=ps1auth-web.socket.j2 dest=/etc/systemd/system/ps1auth-web.socket

#- name: profit??
